artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Devansh444/Datasets/raw/refs/heads/main/brain_tumor_dataset-20250810T140801Z-1-001.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_transformation:
  root_dir: artifacts/data_transformation
  train_data_dir: artifacts/data_ingestion/brain_tumor_dataset/train
  test_data_dir: artifacts/data_ingestion/brain_tumor_dataset/test
